### ISSUE TITLE
使用中 主线程卡死

### ISSUE THREAD

**Issue by xiajinchun** [Dalodd/Alamofire-Synchronous#1]
作者你好，
我在使用的时候，不管是放在主线程中还是回调中，都会导致主线程以及界面卡死，而且一直返回不了数据，请问你在使用的过程中遇到这样的问题吗？
我用的是Swift2.1  Xcode7.1.1  iOS9.1
谢谢！

**Comment by Dalodd** [comment]
不能在主线程里用啊。。

**Comment by xiajinchun** [comment]
放在主线程的话，只要等数据回来了不就好了吗？为什么回一直在卡死的状态哇？

**Comment by Dalodd** [comment]
Main Queue比较特别，是个顺序执行队列，里面的内容并不会并发执行。。

**Comment by Dalodd** [comment]
dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER)
所以Main Queue会卡在这一句，一直等待信号，而原本应该并发执行的Alamofire并没有被执行，你看一下源码应该就理解了

**Comment by xiajinchun** [comment]
嗯，多谢
我想了解一下那这个同步请求当应该放在何处合适呢？
我使用的场景是 在请求任何API的时候需要首先取得 token ， 所以在第一次获取 token 的时候需要同步的来请求 token ，然后再调用API
如果不放在 主线程 那要该如何做啊，我是新手，给个思路就行哈
多谢作者了 :+1:

**Comment by zhuangluda** [comment]
把这一堆都放后台就好了

**Comment by zhuangluda** [comment]
```swift
dispatch_async(dispatch_get_global_queue(QOS_CLASS_BACKGROUND, 0)) {
            let response = Alamofire.request(.GET, "https://httpbin.org/stream/100").responseJSON()
            if let json = response.result.value {
                //something else
                dispatch_async(dispatch_get_main_queue()) {
                    //update UI
                }
            }
        }
```
大致就这样, 主线程不应该放这种耗时的工作的
另外要实现在主线程中使用的话要修改Alamofire源码，就没有必要了。。。
