### ISSUE TITLE
Response doesn't load. It goes into the sleep  state forever.

### ISSUE THREAD

**Issue by asifbilal-vteams** [Dalodd/Alamofire-Synchronous#3]
It just sleeps when calling any request. And never gets back. It just calls "dispatch_semaphore_wait" and then never comes to the success block.

**Comment by Dalodd** [comment]
Don't use it in main queue.

**Comment by asifbilal-vteams** [comment]
If i use "dispatch_async", then it won't be synchronous request anymore.

**Comment by Dalodd** [comment]
You shouldn't and actually you can't block main queue in iOS. Alamofire can do all the things that this component can do.It just provides another way to code.

**Comment by Dalodd** [comment]
Sorry! Fixed it.
