### ISSUE TITLE
Create a Pod Namespace for the extension

### ISSUE THREAD

**Issue by Pycnomerus** [Dalodd/Alamofire-Synchronous#4]
it would be fun to have a way to not always use the extension in a given solution.

also we didn't find a way to use the pods without copying the code in the solution...

**Comment by Dalodd** [comment]
Sorry!
You mean, you want use `pod 'Alamofire-Synchronous'` instead of `pod 'Alamofire-Synchronous', :git => 'https://github.com/Dalodd/Alamofire-Synchronous.git'`?

**Comment by Pycnomerus** [comment]
Well there's that but in the code, enabling the extension by using 
import AlamofireSynchronous instead of having to copy paste the .swift file in the project. allowing us to decide when the call are Synchronous and when it should be Asynchronous.

**Comment by Dalodd** [comment]
When using cocoapods, there's no need to copy the .swift file into your project. You can import it this way where you need to use this extension:

```
import Alamofire
import Alamofire_Synchronous
```

and the Synchronous method doesn't have the `completionHandler` parameter, when you provide one, it becomes Asynchronous method.

Example:

```
// Synchronous, and don't forgot the return value
Alamofire.request(.GET, "https://httpbin.org/get").responseJSON()

// Synchronous, and don't forgot the return value
Alamofire.request(.GET, "https://httpbin.org/get").responseJSON(options: .AllowFragments)

// Asynchronous
Alamofire.request(.GET, "https://httpbin.org/get").responseJSON { (response) in
}

// Asynchronous
let completionHandler: (Response<AnyObject, NSError> -> Void) = { response in
}
Alamofire.request(.GET, "https://httpbin.org/get").responseJSON(queue: nil, options: .AllowFragments, completionHandler: completionHandler)
```

I hope it will be helpful to you.
