### ISSUE TITLE
Swift 3 - Extra argument in call ?

### ISSUE THREAD

**Issue by ins0u** [Dalodd/Alamofire-Synchronous#6]
Hello,

I have a little problem with Alamofire-Synchronous..

1/ To use this library in my project, i drag and drop "Alamofire+Synchronous.swift" to the project tree
2/ When i want to use, I have a error "Extra argument in call" 

My code :

`let Paramètres = [
            "Login": textfieldLogin.text!,
            "Password" : textfieldMotDePasse.text!
        ]
let recupJsonSync = Alamofire.request(method: .POST, "http://www.myurl.com/api/login", parameters: Paramètres).responseJSON()`

Have you an idea for solve my problem ?

Thank you for your help :)

**Comment by Dalodd** [comment]
Swift 3 and Alamofire 4?

**Comment by ins0u** [comment]
Yes and yes :)

**Comment by Dalodd** [comment]
Try this:

```
let recupJsonSync = Alamofire.request("http://www.myurl.com/api/login", method: .POST, parameters: Paramètres).responseJSON()
```

Maybe you should read this document: https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md

**Comment by GZaccaroni** [comment]
@Dalodd , @ins0u Correct syntax is
`let recupJsonSync = Alamofire.request("http://www.myurl.com/api/login", method: .post, parameters: Paramètres).responseJSON()
`
because now post is lowercase. I have updated the documentation of AlamofireSynchronous accordingly.

**Comment by ins0u** [comment]
Thx, it works perfectly 😄
