### ISSUE TITLE
Problem install pod

### ISSUE THREAD

**Issue by francescoscaringi** [Dalodd/Alamofire-Synchronous#8]
I have insert in my podfile both "Alamofire" and "Alamofire-Synchronous":
pod 'Alamofire', '~> 4.0'
pod 'Alamofire-Synchronous', '~> 4.0'

When i try to install the podfile, I'll give this error:
"[!] Unable to satisfy the following requirements:
- `Alamofire-Synchronous (~> 4.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Alamofire-Synchronous (~> 4.0)`.

You have either:
- out-of-date source repos which you can update with `pod repo update`.
- mistyped the name or version.
- not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default."

I've also update CocoaPods to last version.

Has anyone encountered the same problem?

**Comment by Dalodd** [comment]
I met some problems when I was pushing to pod chunk.And it's fixed now.sry about that!!

**Comment by francescoscaringi** [comment]
Yes, now it working! Thx
